---
- hosts: localhost
  connection: local
  become: no
  gather_facts: yes
  vars:
    ecs_cluster_name: sg_gearup_dev
    ecs_alb_name: sg-dev-test
    ecs_asg_name: "{{ ecs_cluster_name }}-asg"

  tasks:
  - name: "AWS | EC2 | Decomission the EC2 Auto Scaling Group"
    ec2_asg:
      name: "{{ ec2_asg_name }}"
      state: "absent"
  - name: "AWS | ASG | Decomission the EC2 Launch Configuration"
    ec2_lc:
      name:  "{{ ecs_cluster_name }}-lc"
      state: "absent"
  - name: "AWS | ECS | Decommission the cluster"
    ecs_cluster:
      name: "{{ ecs_cluster_name }}"
      state: "absent"  
# Delete a target group
  - name: Delete ECS ELB Target Group
    elb_target_group:
      name:  '{{ecs_alb_name}}-targetgroup'
      state: absent
  - name: Delete APP- ELB
    elb_application_lb:
      state: absent
      name: '{{ecs_alb_name}}-App'
